### ISSUE TITLE
You must provide ssh information to correctly connect to a remote server

### ISSUE THREAD

**Issue by tyssen** [khaliqgant/remotee-sync#1]
I have a remotee-sync.json file set up that looks like:

```
{
"ssh" : {
  "production" : "user@xxx.xxx.xxx.xxx"
},
"location": "/Users/…/…",
"dumpName" : "db.sql",
"save" : "yes",
"database" : {
  "local" : {
    "hostname" : "",
    "username" : "",
    "password" : "",
    "database" : ""
  },
  "production" : {
    "hostname" : "",
    "username" : "",
    "password" : "",
    "database" : ""
  }
}
```

  }

but I keep getting the error in the title. I know the user@server details are correct so is there something else about the config file which is incorrect?

**Comment by khaliqgant** [comment]
Thanks for the issue. What is the command that you are attempting to run? Perhaps you aren't specifying which environment it should be ssh'ing to?

If you have the information in the remotee-sync.json file then it should be

`remotee-sync --env=production`

**Comment by tyssen** [comment]
Ah yes, that was it. I thought with a config file that I didn't need to add any other options on the command line.

**Comment by khaliqgant** [comment]
Ok great. I suppose if only one environment is specified in the config file, it could infer where the ssh connection should happen. I'll add that logic in on the next update. Let me know any other issues or questions!
