### ISSUE TITLE
Support Non-MAMP MySQL installation.

### ISSUE THREAD

**Issue by julianfann** [khaliqgant/remotee-sync#10]
It would be great to support an alternate mysql binary path instead of just an alternate MAMP path in a remotee-sync.json file. I may be able to help implement this soon.

**Comment by khaliqgant** [comment]
Thanks @julianfann. Just updated the [package](https://www.npmjs.com/package/remotee-sync) to version 1.2.3 to resolve this and https://github.com/khaliqgant/remotee-sync/issues/9. Let me know if you see any issues!
